version: '3.8'

services:
  frontend:
    build: ./rsse-frontend
    container_name: rsse-frontend
    ports:
      - '3000:3000'
  backend:
    build: ./rsse-strapi
    container_name: rsse-strapi
    ports:
      - '1337:1337'
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: rsse-db
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi-db-data:/var/lib/postgresql/data
  nginx:
    image: nginx:1.19-alpine
    container_name: rsse-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  strapi-db-data:
